-- Create Contacts Table
create table public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  phone text,
  company text,
  message text,
  status text default 'New'::text
);

-- Create Leads Table
create table public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  phone text,
  interest text,
  status text default 'New'::text
);

-- Create Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer text,
  email text,
  plan text,
  amount text,
  status text default 'Completed'::text,
  payment_id text
);

-- Enable Row Level Security (RLS)
alter table public.contacts enable row level security;
alter table public.leads enable row level security;
alter table public.orders enable row level security;

-- Create Policies (Allow Public Insert, Allow Anon Select/Update/Delete for now for simplicity of this static app)
-- IN PRODUCTION, you would want stricter auth, but for this specific "Admin Key" usage on client side or just open for demo:
-- We will allow anyone to INSERT (for the contact form)
create policy "Enable insert for everyone" on public.contacts for insert with check (true);
create policy "Enable insert for everyone" on public.leads for insert with check (true);
create policy "Enable insert for everyone" on public.orders for insert with check (true);

-- We will allow anyone to SELECT/UPDATE/DELETE (since the dashboard is password protected via client-side PIN, checking credentials there is tricky without real Auth)
-- Ideally, we'd use Supabase Auth. For now, to match the current scope:
create policy "Enable read access for all users" on public.contacts for select using (true);
create policy "Enable update for all users" on public.contacts for update using (true);
create policy "Enable delete for all users" on public.contacts for delete using (true);

create policy "Enable read access for all users" on public.leads for select using (true);
create policy "Enable update for all users" on public.leads for update using (true);
create policy "Enable delete for all users" on public.leads for delete using (true);

create policy "Enable read access for all users" on public.orders for select using (true);
create policy "Enable update for all users" on public.orders for update using (true);
create policy "Enable delete for all users" on public.orders for delete using (true);
