-- SQL SCHEMA FOR THE WEBPAGE BUILDER LEADS DATABASE
-- Run this migration script in your Supabase project's SQL Editor (https://supabase.com/dashboard/project/_/sql)
-- This script will safely create or migrate your existing 'leads' table to include all required fields.

-- 1. Create the Leads table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT,
    phone TEXT,
    status TEXT DEFAULT 'new'
);

-- 2. Safely add missing columns for The Webpage Builder React app if they don't exist
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS company TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS message TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS vision TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS challenge TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS requirements TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS "projectType" TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS timeline TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS budget TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'contact';
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS "scheduledDate" TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS "scheduledTime" TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS "paymentReference" TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS "paymentDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS "invoiceGenerated" BOOLEAN DEFAULT false;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS "gstApplicable" BOOLEAN DEFAULT false;
-- 3. Enable Row Level Security (RLS) on the table
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies (Safely checks if policies already exist)

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'leads' AND policyname = 'Allow public inserts'
    ) THEN
        CREATE POLICY "Allow public inserts" ON public.leads FOR INSERT TO anon WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'leads' AND policyname = 'Allow authenticated selects'
    ) THEN
        CREATE POLICY "Allow authenticated selects" ON public.leads FOR SELECT TO authenticated USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'leads' AND policyname = 'Allow authenticated updates'
    ) THEN
        CREATE POLICY "Allow authenticated updates" ON public.leads FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'leads' AND policyname = 'Allow authenticated deletes'
    ) THEN
        CREATE POLICY "Allow authenticated deletes" ON public.leads FOR DELETE TO authenticated USING (true);
    END IF;
END
$$;
